/**
 * @fileoverview EntitySchema.js
 * Defines the core vocabulary and data structures for the Medicine Intelligence Agent.
 * This is the sacred schema that all subsystems (WorldModel, Reasoning, Evidence Attribution)
 * depend on. It ensures the system reasons about "Entities", not "Pixels".
 */

/**
 * Represents a physical or logical region on the medicine packaging.
 * Regions are the foundational building blocks of the World Model.
 * @typedef {Object} Region
 * @property {string} id - Unique identifier for the region (e.g., 'reg-1234')
 * @property {string} type - e.g., 'FOIL', 'BLISTER_CAVITY', 'TEXT_BLOCK', 'MANUFACTURER_LOGO', 'UNKNOWN'
 * @property {Object} boundingVolume - 3D approximation of the region's physical space {x, y, z, width, height, depth}
 * @property {boolean} isOccluded - Whether the region is currently hidden from view
 * @property {number} observabilityScore - 0.0 to 1.0 (how well can we see this right now?)
 * @property {Object} spatialAnchor - Optional link to the SpatialAnchoringEngine tracking ID
 */

/**
 * An atomic unit of evidence generated by a subsystem.
 * @typedef {Object} Evidence
 * @property {string} id - Unique identifier
 * @property {string} source - e.g., 'OCR_ENGINE', 'SHAPE_ANALYZER', 'KNOWLEDGE_GRAPH'
 * @property {string} type - e.g., 'TEXT_MATCH', 'GEOMETRY_MATCH', 'RELATIONSHIP_VERIFIED'
 * @property {string|null} regionId - The specific Region this evidence is anchored to (if any)
 * @property {any} payload - The raw data (e.g., { text: 'Paracetamol', confidence: 0.92 })
 * @property {number} timestamp - When this evidence was acquired
 */

/**
 * A transaction in the Evidence Attribution Engine.
 * Represents a subsystem bidding points for or against a hypothesis.
 * @typedef {Object} LedgerEntry
 * @property {string} id - Unique identifier
 * @property {string} evidenceId - Link to the Evidence that triggered this
 * @property {string} targetHypothesisId - The candidate being supported/penalized
 * @property {number} points - The weighted score added or subtracted (e.g., +12, -5)
 * @property {string} rationale - Human readable reason (e.g., "Manufacturer logo matches expected packaging")
 * @property {number} timestamp - Transaction time
 */

/**
 * A competing candidate identification maintained by the Reasoning Engine.
 * @typedef {Object} Hypothesis
 * @property {string} id - Unique identifier (usually the medicine ID from the knowledge graph)
 * @property {string} name - Human readable name (e.g., 'Paracetamol 650mg')
 * @property {number} confidenceScore - 0.0 to 1.0 (derived from the sum of LedgerEntries)
 * @property {Array<string>} supportingEvidenceIds - Evidence validating this hypothesis
 * @property {Array<string>} contradictoryEvidenceIds - Evidence penalizing this hypothesis
 * @property {Array<string>} missingCriticalRegions - What we still need to see to reach 0.95+ confidence
 */

/**
 * Forecast generated by the Prediction Engine.
 * @typedef {Object} Prediction
 * @property {string} type - e.g., 'DEPLETION_FORECAST', 'CONSUMPTION_EVENT'
 * @property {any} previousState - e.g., { cavityCount: 10, filled: 10 }
 * @property {any} currentState - e.g., { cavityCount: 10, filled: 8 }
 * @property {any} forecastedState - e.g., { consumed: 2, estimatedDaysRemaining: 4 }
 * @property {number} confidence - 0.0 to 1.0
 */

/**
 * The persistent Digital Twin representing the medicine object in the real world.
 * @typedef {Object} Entity
 * @property {string} id - Unique identifier (e.g., 'entity-7842')
 * @property {string} classification - High level type (e.g., 'BLISTER_PACK', 'BOTTLE', 'CARTON', 'UNKNOWN')
 * @property {Map<string, Region>} regions - Map of all discovered regions
 * @property {Array<Evidence>} evidenceLog - Chronological history of all acquired evidence
 * @property {Map<string, Hypothesis>} hypotheses - The active candidates being evaluated
 * @property {string|null} leadingHypothesisId - The ID of the current winner
 * @property {Array<Prediction>} predictions - Forecasting history
 * @property {number} creationTime - When the lock was first acquired
 * @property {number} lastUpdated - Last state mutation
 */

export const SchemaTypes = {
  REGION: 'REGION',
  EVIDENCE: 'EVIDENCE',
  LEDGER_ENTRY: 'LEDGER_ENTRY',
  HYPOTHESIS: 'HYPOTHESIS',
  PREDICTION: 'PREDICTION',
  ENTITY: 'ENTITY'
};
